# .github/workflows/test-single.yml
name: Test
 
on:
  workflow_dispatch:
    inputs:
      email:
        type: string
        required: true
      password:
        type: string
        required: true
      membership-code:
        type: string
        required: true
 
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
 
    services:
      selenium:
        image: selenium/standalone-chrome
 
    steps:
      - uses: actions/checkout@v2
 
      - run: node actions/membership.mjs
        env:
          BROWSER: chrome
 
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: screenshots/